{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "188d7b63",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import folium\n",
    "from streamlit_folium import st_folium\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"แผนที่วัดเชียงใหม่\",\n",
    "    page_icon=\"⛩\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "temples = [\n",
    "    {\n",
    "        \"id\": 1,\n",
    "        \"name\": \"วัดพระธาตุดอยสุเทพราชวรวิหาร\",\n",
    "        \"lat\": 18.8048,\n",
    "        \"lng\": 98.9216,\n",
    "        \"history\": \"วัดพระธาตุดอยสุเทพราชวรวิหาร เป็นปูชนียสถานที่สำคัญและเป็นสัญลักษณ์ของเมืองเชียงใหม่มาช้านาน สร้างขึ้นตั้งแต่สมัยพญากือนาเมื่อกว่า 600 ปีที่แล้ว ภายในวัดเป็นที่ประดิษฐานขององค์พระเจดีย์ทรงเชียงแสนสีทองอร่าม ที่บรรจุพระบรมสารีริกธาตุขององค์สมเด็จพระสัมมาสัมพุทธเจ้าไว้\",\n",
    "        \"famous\": \"มีความเชื่อว่าหากได้มากราบไหว้สักการะครบทั้งสี่ทิศ พร้อมเดินเวียนขวา 3 รอบ จะช่วยให้ชีวิตพบเจอแต่ความราบรื่นและประสบความสำเร็จตามที่ปรารถนา\",\n",
    "        \"category\": \"พระธาตุ\",\n",
    "        \"color\": \"#D4A017\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 2,\n",
    "        \"name\": \"วัดอุโมงค์ (สวนพุทธธรรม)\",\n",
    "        \"lat\": 18.7779,\n",
    "        \"lng\": 98.9676,\n",
    "        \"history\": \"วัดโบราณที่สร้างขึ้นตั้งแต่สมัยพญามังราย มีอายุเก่าแก่กว่า 700 ปี จุดเด่นของวัดแห่งนี้คือ อุโมงค์เก่าแก่ ที่สร้างขึ้นในสมัยพญากือนาเพื่อถวายให้พระมหาเถรจันทร์ได้ใช้เป็นสถานที่ปฏิบัติธรรม ภายในอุโมงค์เป็นทางเดินเชื่อมถึงกันหลายช่อง\",\n",
    "        \"famous\": \"เหมาะสำหรับผู้ที่ต้องการขอพรให้ชีวิตได้พบเจอหนทางใหม่ หรือเริ่มต้นสิ่งดี ๆ อีกครั้ง บรรยากาศเงียบสงบ ร่มรื่นไปด้วยต้นไม้นานาพันธุ์\",\n",
    "        \"category\": \"วัดสมาธิ\",\n",
    "        \"color\": \"#2E7D32\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 3,\n",
    "        \"name\": \"วัดพระธาตุดอยคำ\",\n",
    "        \"lat\": 18.7674,\n",
    "        \"lng\": 98.9425,\n",
    "        \"history\": \"วัดเก่าแก่ที่มีอายุมากกว่า 1,300 ปี ตั้งอยู่บนเนินเขาสูงจากตัวเมือง ซึ่งในอดีตสร้างขึ้นในสมัยพระนางจามเทวี และเป็นที่รู้จักกันในนาม วัดสุวรรณบรรพต\",\n",
    "        \"famous\": \"พระพุทธรูปหลวงพ่อทันใจ มีชื่อเสียงโดดเด่นในเรื่องความศักดิ์สิทธิ์มากที่สุด โดยเฉพาะในด้านการเงิน การงาน โชคลาภ และการเสี่ยงโชค\",\n",
    "        \"category\": \"พระธาตุ\",\n",
    "        \"color\": \"#D4A017\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 4,\n",
    "        \"name\": \"วัดป่าแดด\",\n",
    "        \"lat\": 18.7533,\n",
    "        \"lng\": 98.9873,\n",
    "        \"history\": \"วัดที่เหมาะสำหรับผู้ที่ต้องการขอพรเรื่องการงาน ความสำเร็จ และความก้าวหน้าในชีวิต ภายในวัดมีเอกสารแนะนำขั้นตอนการไหว้ขอพรให้สมหวัง\",\n",
    "        \"famous\": \"ขึ้นชื่อเรื่องความศักดิ์สิทธิ์ของ องค์พระพิฆเนศ หรือที่รู้จักกันในนาม อุตรศรีคณปติ ซึ่งเป็นเทพเจ้าแห่งความสำเร็จและผู้ขจัดอุปสรรคทั้งปวง\",\n",
    "        \"category\": \"วัดมงคล\",\n",
    "        \"color\": \"#C62828\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 5,\n",
    "        \"name\": \"วัดอุปคุต\",\n",
    "        \"lat\": 18.7797,\n",
    "        \"lng\": 98.9984,\n",
    "        \"history\": \"วัดศักดิ์สิทธิ์เชียงใหม่ที่ตั้งอยู่ในย่านช้างคลาน ขึ้นชื่อเรื่องการขอพรจาก พระอุปคุต ซึ่งประดิษฐานอยู่บนวิหาร ผู้ที่มาสักการะเชื่อกันว่าการขอพรจากพระอุปคุตจะช่วยเปิดทางให้ชีวิตเจริญรุ่งเรือง\",\n",
    "        \"famous\": \"ประเพณีตักบาตรเที่ยงคืน หรือที่ชาวล้านนาเรียกว่า ตักบาตรเป็งปุ๊ด ซึ่งจัดขึ้นเฉพาะในคืนวันเพ็ญที่ตรงกับวันพุธเท่านั้น\",\n",
    "        \"category\": \"วัดมงคล\",\n",
    "        \"color\": \"#C62828\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 6,\n",
    "        \"name\": \"วัดเจดีย์หลวงวรวิหาร\",\n",
    "        \"lat\": 18.7868,\n",
    "        \"lng\": 98.9872,\n",
    "        \"history\": \"วัดเก่าแก่ที่มีความสำคัญทางประวัติศาสตร์และสถาปัตยกรรมมาอย่างยาวนานกว่า 600 ปี ใจกลางเมืองเชียงใหม่ เป็นที่ประดิษฐานของพระเจดีย์หลวง ซึ่งเคยเป็นเจดีย์ที่ใหญ่ที่สุดในภาคเหนือ มีความสูงถึง 92 เมตร\",\n",
    "        \"famous\": \"มีศาลหลักเมือง หรือเสาอินทขิล สร้างความมั่นคงให้ชาวเชียงใหม่ และ ท้าวเวสสุวรรณ ที่นิยมในการขอพรเพื่อความเป็นสิริมงคลและความเจริญรุ่งเรือง\",\n",
    "        \"category\": \"วัดประวัติศาสตร์\",\n",
    "        \"color\": \"#6A1B9A\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 7,\n",
    "        \"name\": \"วัดพระสิงห์วรมหาวิหาร\",\n",
    "        \"lat\": 18.7874,\n",
    "        \"lng\": 98.9836,\n",
    "        \"history\": \"พระอารามหลวงชั้นเอกที่ตั้งอยู่ใจกลางคูเมืองเชียงใหม่ มีประวัติยาวนานกว่า 600 ปี สร้างขึ้นโดยพญาผายู กษัตริย์องค์ที่ 5 แห่งราชวงศ์มังราย\",\n",
    "        \"famous\": \"เป็นที่ประดิษฐานของ พระพุทธสิหิงค์ หรือ พระสิงห์ ขึ้นชื่อเรื่องความเมตตาและเสน่ห์เมตตามหานิยม ทำให้มีแต่คนรักใคร่และเอ็นดู เป็นวัดประจำปีเกิดของคนปีมะโรง\",\n",
    "        \"category\": \"พระอารามหลวง\",\n",
    "        \"color\": \"#E65100\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 8,\n",
    "        \"name\": \"วัดดวงดี\",\n",
    "        \"lat\": 18.7892,\n",
    "        \"lng\": 98.9881,\n",
    "        \"history\": \"เดิมชื่อ วัดต้นหมากเหนือ ตั้งอยู่ในเขตเมืองเก่าของเชียงใหม่ โดดเด่นด้วยสถาปัตยกรรมแบบล้านนาอันงดงามที่สร้างจากไม้แกะสลักอย่างประณีต มีอายุยาวนานกว่า 100 ปี\",\n",
    "        \"famous\": \"ชื่อเป็นมงคล ขึ้นชื่อเรื่องการขอพรให้โชคดีในด้านการเงินและโชคลาภ สายมูนิยมมาเสริมดวงชะตาและปัดเป่าความโชคร้าย\",\n",
    "        \"category\": \"วัดมงคล\",\n",
    "        \"color\": \"#C62828\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 9,\n",
    "        \"name\": \"วัดลอยเคราะห์\",\n",
    "        \"lat\": 18.7841,\n",
    "        \"lng\": 98.9936,\n",
    "        \"history\": \"เดิมชื่อ วัดร้อยข้อ สร้างขึ้นในสมัยพญากือนาเมื่อกว่า 500 ปีที่แล้ว ตั้งอยู่ใจกลางเมืองเชียงใหม่ โดดเด่นด้วยสถาปัตยกรรมแบบล้านนาอันงดงาม\",\n",
    "        \"famous\": \"เป็นที่ประดิษฐานของ พระพุทธศุภโชคศรีลอยเคราะห์มิ่งมงคล และ พระเจ้าทันใจ นิยมมากราบไหว้เพื่อเสริมดวงชะตา ลอยเคราะห์ ลอยโศก\",\n",
    "        \"category\": \"วัดมงคล\",\n",
    "        \"color\": \"#C62828\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 10,\n",
    "        \"name\": \"วัดหมื่นล้าน\",\n",
    "        \"lat\": 18.7882,\n",
    "        \"lng\": 98.9899,\n",
    "        \"history\": \"หรือ วัดหมื่นสามล้าน ตั้งอยู่บนถนนราชดำเนิน สร้างขึ้นในช่วงรัชสมัยพระเจ้าติโลกราช เพื่ออุทิศส่วนบุญกุศลให้แก่แม่ทัพที่เสียชีวิตในสนามรบ\",\n",
    "        \"famous\": \"ชื่อวัดสื่อถึงความมั่งคั่ง ผู้คนนิยมมาขอพรด้านการเงิน โชคลาภ โดดเด่นด้วยสถาปัตยกรรมแบบพม่าผสมล้านนา มีลวดลายไม้แกะสลักรูปนกยูงรำแพน\",\n",
    "        \"category\": \"วัดประวัติศาสตร์\",\n",
    "        \"color\": \"#6A1B9A\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 11,\n",
    "        \"name\": \"วัดล่ามช้าง\",\n",
    "        \"lat\": 18.7843,\n",
    "        \"lng\": 98.9853,\n",
    "        \"history\": \"วัดราษฎร์เก่าแก่ที่สร้างขึ้นในสมัยพญามังรายตั้งแต่ปี พ.ศ. 1839 ชื่อของวัดได้มาจากการที่ในอดีตเคยเป็นสถานที่ล่ามช้างคู่พระบารมีของกษัตริย์\",\n",
    "        \"famous\": \"พระเจ้ามุกดอกไม้ สมปรารถนาศรีเมืองเชียงใหม่ สร้างจากดอกไม้แห้งผสมมวลสารศักดิ์สิทธิ์ เชื่อว่าหากได้กลิ่นหอมอ่อน ๆ ของดอกไม้ จะช่วยให้เรื่องร้ายกลายเป็นดี\",\n",
    "        \"category\": \"วัดประวัติศาสตร์\",\n",
    "        \"color\": \"#6A1B9A\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 12,\n",
    "        \"name\": \"วัดดับภัย\",\n",
    "        \"lat\": 18.7862,\n",
    "        \"lng\": 98.9914,\n",
    "        \"history\": \"เดิมมีชื่อว่า วัดอภัย หรือ วัดตุงกระด้าง เป็นที่ประดิษฐานของ พระเจ้าดับภัย พระพุทธรูปศักดิ์สิทธิ์ที่เชื่อกันว่ามีอานุภาพในการขจัดปัดเป่าทุกข์ภัยและโรคภัยไข้เจ็บ\",\n",
    "        \"famous\": \"มีกิจกรรมพิธีสืบชะตาสะเดาะเคราะห์ในช่วงเดือนพฤษภาคมของทุกปี ผู้คนนิยมมาสักการะเพื่อสะเดาะเคราะห์และเสริมดวงชะตา\",\n",
    "        \"category\": \"วัดมงคล\",\n",
    "        \"color\": \"#C62828\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 13,\n",
    "        \"name\": \"วัดโลกโมฬี\",\n",
    "        \"lat\": 18.7944,\n",
    "        \"lng\": 98.9821,\n",
    "        \"history\": \"วัดเก่าแก่กว่า 500 ปี ย่านคูเมืองเชียงใหม่ โดดเด่นด้วยวิหารไม้สักสถาปัตยกรรมล้านนา และเจดีย์โบราณที่งดงาม บรรยากาศสงบร่มเย็น\",\n",
    "        \"famous\": \"เป็นที่นิยมในการมาสักการะ พระนางจิรประภามหาเทวี เพื่อขอพรด้านความรัก ความราบรื่นในการงานและชีวิต และชมโคมยี่เป็งหลากสีในช่วงปลายปี\",\n",
    "        \"category\": \"วัดประวัติศาสตร์\",\n",
    "        \"color\": \"#6A1B9A\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 14,\n",
    "        \"name\": \"วัดพันเตา\",\n",
    "        \"lat\": 18.7863,\n",
    "        \"lng\": 98.9884,\n",
    "        \"history\": \"สร้าง พ.ศ.1934 เคยเป็นเขตสังฆาวาสของวัดโชติการาม (วัดเจดีย์หลวง) สันนิษฐานว่าบริเวณที่ตั้งเคยเป็นสถานที่ตั้งเส้าพันเตา เป็นเตาที่ใช้หลอมทองหล่อพระอัฎฐารส\",\n",
    "        \"famous\": \"จุดเด่นวิหารหอคำ สร้างด้วยไม้สัก ภายในประดิษฐาน พระเจ้าปันเต้า มีความหมายว่า มีความสำเร็จเพิ่มพูนเป็นร้อยเท่าพันเท่า\",\n",
    "        \"category\": \"วัดประวัติศาสตร์\",\n",
    "        \"color\": \"#6A1B9A\",\n",
    "    },\n",
    "    {\n",
    "        \"id\": 15,\n",
    "        \"name\": \"วัดเด่นสะหลีศรีเมือง\",\n",
    "        \"lat\": 18.7959,\n",
    "        \"lng\": 98.9742,\n",
    "        \"history\": \"เดิมชื่อวัดบ้านเด่น ตั้งแต่ครูบาเจ้าเทืองมาจำพรรษา จากที่ไม่เคยมีต้นโพธิ์เลยก็มีต้นโพธิ์ขึ้นมากมาย ชาวเมืองเหนือเรียกต้นโพธิ์ว่า ต้นสะหลี ซึ่งมีความหมายว่าเป็นมงคลดี\",\n",
    "        \"famous\": \"วัดตั้งอยู่ในเขตเมืองเก่าโบราณชื่อเมืองแกน ชาวบ้านเรียกชื่อเต็มว่า วัดเด่นสะหลีศรีเมืองแกน ขึ้นชื่อเรื่องต้นโพธิ์ศักดิ์สิทธิ์และความเป็นมงคล\",\n",
    "        \"category\": \"วัดมงคล\",\n",
    "        \"color\": \"#C62828\",\n",
    "    },\n",
    "]\n",
    "\n",
    "category_colors = {\n",
    "    \"พระธาตุ\": \"#D4A017\",\n",
    "    \"วัดสมาธิ\": \"#2E7D32\",\n",
    "    \"วัดมงคล\": \"#C62828\",\n",
    "    \"วัดประวัติศาสตร์\": \"#6A1B9A\",\n",
    "    \"พระอารามหลวง\": \"#E65100\",\n",
    "}\n",
    "\n",
    "# --- Header ธีมล้านนา ---\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .stApp { background-color: #FBF0DC; }\n",
    "    .lanna-header {\n",
    "        background: linear-gradient(135deg, #6B2D2D 0%, #8B3A3A 40%, #A0522D 100%);\n",
    "        border-bottom: 3px solid #D4A017;\n",
    "        padding: 16px 24px;\n",
    "        border-radius: 8px;\n",
    "        margin-bottom: 16px;\n",
    "        text-align: center;\n",
    "        box-shadow: 0 2px 12px rgba(0,0,0,0.35);\n",
    "    }\n",
    "    .lanna-title { color: #FFF3D0; font-size: 2rem; font-weight: 700; margin: 0; }\n",
    "    .lanna-subtitle { color: #D4A017; font-size: 1rem; margin: 4px 0 0; }\n",
    "    .lanna-ornament { color: #D4A017; font-size: 1.3rem; }\n",
    "    .temple-card {\n",
    "        background: #FFF8EC;\n",
    "        border: 1.5px solid rgba(212,160,23,0.3);\n",
    "        border-radius: 8px;\n",
    "        padding: 10px 12px;\n",
    "        margin-bottom: 6px;\n",
    "        cursor: pointer;\n",
    "    }\n",
    "    .temple-card:hover { border-color: #D4A017; background: #FFF3D0; }\n",
    "    .popup-title { font-weight: 700; font-size: 1rem; margin: 0 0 6px; }\n",
    "    .popup-section { margin-top: 8px; }\n",
    "    .popup-label { font-weight: 700; color: #6B2D2D; font-size: 0.85rem; }\n",
    "    .popup-text { font-size: 0.85rem; line-height: 1.5; color: #3B1A00; }\n",
    "    div[data-testid=\"stSidebar\"] { background-color: #F5E6C8; }\n",
    "    </style>\n",
    "    <div class=\"lanna-header\">\n",
    "        <div>\n",
    "            <p class=\"lanna-ornament\">✦ ✦ ✦</p>\n",
    "            <h1 class=\"lanna-title\">⛩ แผนที่วัดเชียงใหม่</h1>\n",
    "            <p class=\"lanna-subtitle\">15 วัดชื่อดังแห่งดินแดนล้านนา</p>\n",
    "        </div>\n",
    "    </div>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# --- Sidebar: รายชื่อวัด + กรองหมวดหมู่ ---\n",
    "with st.sidebar:\n",
    "    st.markdown(\"## 🗺️ รายชื่อวัด\")\n",
    "    categories = [\"ทั้งหมด\"] + list(category_colors.keys())\n",
    "    selected_category = st.selectbox(\"กรองตามหมวดหมู่\", categories)\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    filtered = temples if selected_category == \"ทั้งหมด\" else [t for t in temples if t[\"category\"] == selected_category]\n",
    "\n",
    "    selected_temple = None\n",
    "    for temple in filtered:\n",
    "        color = category_colors.get(temple[\"category\"], \"#C62828\")\n",
    "        label = f\"**{temple['id']}.** {temple['name']}\"\n",
    "        if st.button(label, key=f\"btn_{temple['id']}\", use_container_width=True):\n",
    "            selected_temple = temple\n",
    "            st.session_state[\"selected_id\"] = temple[\"id\"]\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "    st.markdown(\"**สีตามหมวดหมู่:**\")\n",
    "    for cat, color in category_colors.items():\n",
    "        st.markdown(f\"<span style='color:{color}'>●</span> {cat}\", unsafe_allow_html=True)\n",
    "\n",
    "# --- สร้างแผนที่ Folium ---\n",
    "if \"selected_id\" in st.session_state:\n",
    "    focus = next((t for t in temples if t[\"id\"] == st.session_state[\"selected_id\"]), None)\n",
    "    center = [focus[\"lat\"], focus[\"lng\"]] if focus else [18.7867, 98.9867]\n",
    "    zoom = 16 if focus else 13\n",
    "else:\n",
    "    center = [18.7867, 98.9867]\n",
    "    zoom = 13\n",
    "\n",
    "m = folium.Map(location=center, zoom_start=zoom, tiles=\"OpenStreetMap\")\n",
    "\n",
    "filtered_temples = temples if selected_category == \"ทั้งหมด\" else [t for t in temples if t[\"category\"] == selected_category]\n",
    "\n",
    "for temple in filtered_temples:\n",
    "    color = temple[\"color\"]\n",
    "    popup_html = f\"\"\"\n",
    "    <div style=\"font-family: 'Sarabun', sans-serif; width: 300px;\">\n",
    "        <div style=\"background:{color}; padding:12px 14px; border-radius:6px 6px 0 0;\">\n",
    "            <span style=\"color:rgba(255,255,255,0.8); font-size:0.7rem;\">วัดที่ {temple['id']}</span>\n",
    "            <h2 style=\"color:white; font-size:1rem; margin:4px 0; line-height:1.3;\">{temple['name']}</h2>\n",
    "            <span style=\"background:rgba(255,255,255,0.2); color:white; padding:2px 8px; border-radius:12px; font-size:0.7rem;\">{temple['category']}</span>\n",
    "        </div>\n",
    "        <div style=\"background:#FFFBF2; padding:12px 14px; border-radius:0 0 6px 6px;\">\n",
    "            <p style=\"color:#6B2D2D; font-weight:700; font-size:0.8rem; margin:0 0 4px;\">📜 ประวัติ</p>\n",
    "            <p style=\"font-size:0.8rem; line-height:1.6; color:#3B1A00; margin:0 0 10px;\">{temple['history']}</p>\n",
    "            <p style=\"color:#6B2D2D; font-weight:700; font-size:0.8rem; margin:0 0 4px;\">⭐ เรื่องขึ้นชื่อ</p>\n",
    "            <p style=\"font-size:0.8rem; line-height:1.6; color:#3B1A00; margin:0;\">{temple['famous']}</p>\n",
    "        </div>\n",
    "    </div>\n",
    "    \"\"\"\n",
    "    icon_html = f\"\"\"\n",
    "        <div style=\"\n",
    "            background:{color};\n",
    "            width:36px; height:36px;\n",
    "            border-radius:50% 50% 50% 0;\n",
    "            transform:rotate(-45deg);\n",
    "            border:2px solid white;\n",
    "            box-shadow:0 2px 6px rgba(0,0,0,0.4);\n",
    "            display:flex; align-items:center; justify-content:center;\">\n",
    "            <span style=\"transform:rotate(45deg); font-size:16px;\">⛩</span>\n",
    "        </div>\n",
    "    \"\"\"\n",
    "    folium.Marker(\n",
    "        location=[temple[\"lat\"], temple[\"lng\"]],\n",
    "        popup=folium.Popup(popup_html, max_width=320),\n",
    "        tooltip=f\"⛩ {temple['name']}\",\n",
    "        icon=folium.DivIcon(html=icon_html, icon_size=(36, 36), icon_anchor=(18, 36)),\n",
    "    ).add_to(m)\n",
    "\n",
    "st_folium(m, width=None, height=580, returned_objects=[])\n",
    "\n",
    "st.markdown(\"\"\"\n",
    "    <div style=\"text-align:center; background:#3B1A00; color:#D4A017;\n",
    "                padding:8px; border-radius:6px; margin-top:8px;\n",
    "                font-size:0.8rem; letter-spacing:0.1em;\">\n",
    "        ล้านนา · เชียงใหม่ · ดินแดนแห่งพระธาตุและวัดศักดิ์สิทธิ์\n",
    "    </div>\n",
    "\"\"\", unsafe_allow_html=True)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
